
language: cpp

branches:
    only:
        - travis

# build environment
before_script:
    - cmake --version
    - sudo apt-get update -qq

    # install newer version of openexr
    - sudo add-apt-repository 'deb http://ppa.launchpad.net/irie/openexr/ubuntu precise main'
    - sudo add-apt-repository 'deb http://ppa.launchpad.net/dcthomp/smtk/ubuntu precise main'
    - sudo apt-get update -qq

    - sudo dpkg -r cmake cmake-data
    - sudo apt-get install cmake
    - cmake --version

    # - sudo apt-get install libilmbase-dev libopenexr-dev
    - sudo apt-get install libboost-python-dev libboost-program-options-dev libboost-thread-dev
    - sudo apt-get install libglew-dev
    - sudo apt-get install freeglut3-dev
    - sudo apt-get install libxmu-dev libxi-dev

    - git clone https://github.com/openexr/openexr.git --depth 1
    - cd openexr/IlmBase
    - ./bootstrap
    - ./configure --prefix=/usr/local
    - make
    - sudo make install
    - cd ../../

    - wget http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.15-patch1.tar.bz2 -O /tmp/hdf5.tar.gz
    - tar -xvf /tmp/hdf5.tar.gz
    - cd hdf5-1.8.15-patch1
    - ./configure --prefix=/usr/local
    - make
    - sudo make install
    - cd ..


script:
    - mkdir build && cd build
    - cmake -DUSE_EXAMPLES=ON -DALEMBIC_LIB_USES_BOOST=ON -DUSE_OPENGL=ON -DALEMBIC_SHARED_LIBS=OFF ../
    - make
    # - sudo make install
    - make test
